[env:heltec_wifi_lora_32_V2]
platform = espressif32
board = heltec_wifi_lora_32_V2
framework = arduino
monitor_speed = 115200

build_flags =
    -D REGION_US915
    -D ACTIVE_REGION=LORAMAC_REGION_US915

lib_deps =
    heltecautomation/Heltec ESP32 Dev-Boards @ ^1.1.2